defaults:
  aws:
    accessKeyId:        '...'
    secretAccessKey:    '...'
    region:             us-west-2
  azure:
    account:        jungle
  azureBlob:
    accountName: jungle
    accountKey: '...'
  pulse:
    username:           '...'
    password:           '...'
