defaults:
  # AWS credentials (leave these blank if just running the server)
  aws:
    accessKeyId:        '...'
    secretAccessKey:    '...'
    region:             us-west-2
  # an azure account for table storage
  azure:
    account:            jungle
    accountKey:         '...'
  # an azure account for blob storage (which can be the same)
  azureBlob:
    accountName:        jungle
    accountKey:         '...'
  # pulse credentials - see http://pulseguardian.mozilla.org/
  pulse:
    username:           '...'
    password:           '...'
